# CORE-CR with PPO backbone on Qwen2-Math-7B (Table 8)
# Uses PPO (GAE advantage estimation) instead of GRPO

MODEL_PATH="Qwen/Qwen2-Math-7B"
TRAINER_MODULE="verl.trainer.main_ppo"
ADV_ESTIMATOR="gae"
REWARD_MANAGER="concept_aug"
USE_CONCEPT_FILE=true

NUM_GPUS=2
MAX_RESPONSE_LENGTH=1024
TRAIN_BATCH_SIZE=64
MICRO_BATCH_SIZE=8
TENSOR_PARALLEL_SIZE=1
GPU_MEMORY_UTIL=0.3
LOG_PROB_MICRO_BATCH=16

USE_KL_LOSS=False
REF_PARAM_OFFLOAD=False
GRAD_OFFLOAD=""
OPTIMIZER_OFFLOAD=True

# PPO-specific parameters
USE_PPO=true
PPO_CLIP_RATIO=0.2
PPO_ENTROPY_COEFF=0.001
PPO_GAMMA=1.0
PPO_LAM=0.95
CRITIC_LR=1e-5

SAVE_INFERENCE_ONLY=True
PROJECT_NAME="core-cr-ppo"
