# CORE-KL: Concept-Guided KL-Regularization (Table 2, Row 5)
# Model: Qwen2-Math-7B | lambda_KL=0.03/0.005 | Epochs: 3 | GPUs: 2x H200

MODEL_PATH="Qwen/Qwen2-Math-7B"
TRAINER_MODULE="verl.trainer.main_ppo_kl"
ADV_ESTIMATOR="grpo"
REWARD_MANAGER="kl_enhanced_naive"
USE_CONCEPT_FILE=true

NUM_GPUS=2
MAX_RESPONSE_LENGTH=1024
TRAIN_BATCH_SIZE=128
MICRO_BATCH_SIZE=8
TENSOR_PARALLEL_SIZE=1
GPU_MEMORY_UTIL=0.3
LOG_PROB_MICRO_BATCH=8

USE_KL_LOSS=True
REF_PARAM_OFFLOAD=True
GRAD_OFFLOAD=""
OPTIMIZER_OFFLOAD=False

PROJECT_NAME="core-kl"

# KL enhancement parameters (CORE-KL only)
USE_KL_ENHANCEMENT=true
KL_BASE_LAMBDA=0.01
KL_EFFECTIVE_MULTIPLIER=3.0
KL_INEFFECTIVE_MULTIPLIER=0.5
