# CORE-Base: Standard GRPO on concept-aligned quizzes (Table 2, Row 3)
# Model: Qwen2-Math-7B | Epochs: 3 | GPUs: 2x H200

MODEL_PATH="Qwen/Qwen2-Math-7B"
TRAINER_MODULE="verl.trainer.main_ppo"
ADV_ESTIMATOR="grpo"
REWARD_MANAGER="naive"
USE_CONCEPT_FILE=false

NUM_GPUS=2
MAX_RESPONSE_LENGTH=1024
TRAIN_BATCH_SIZE=128
MICRO_BATCH_SIZE=8
TENSOR_PARALLEL_SIZE=2
GPU_MEMORY_UTIL=0.3
LOG_PROB_MICRO_BATCH=16

USE_KL_LOSS=True
REF_PARAM_OFFLOAD=True
GRAD_OFFLOAD=False
OPTIMIZER_OFFLOAD=False

PROJECT_NAME="core-base"
